Proyecto-AspCore-Web/ProyectoWeb/ProyectoApiCore.Web/Controllers/EquiposController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProyectoApiCore.Web;
using ProyectoApiCore.Web.Contexto;

namespace ProyectoApiCore.Web.Controllers
{
    public class EquiposController : Controller
    {
        private readonly DbContextDatos _context;

        public EquiposController(DbContextDatos context)
        {
            _context = context;
        }

        // GET: Equipos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Equipo.ToListAsync());
        }

        // GET: Equipos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipos = await _context.Equipo
                .FirstOrDefaultAsync(m => m.idEquipo == id);
            if (equipos == null)
            {
                return NotFound();
            }

            return View(equipos);
        }

        // GET: Equipos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Equipos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("idEquipo,nombreEquipo,descripcionEquipo,logoEquipo")] Equipos equipos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(equipos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(equipos);
        }

        // GET: Equipos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipos = await _context.Equipo.FindAsync(id);
            if (equipos == null)
            {
                return NotFound();
            }
            return View(equipos);
        }

        // POST: Equipos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("idEquipo,nombreEquipo,descripcionEquipo,logoEquipo")] Equipos equipos)
        {
            if (id != equipos.idEquipo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(equipos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EquiposExists(equipos.idEquipo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(equipos);
        }

        // GET: Equipos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var equipos = await _context.Equipo
                .FirstOrDefaultAsync(m => m.idEquipo == id);
            if (equipos == null)
            {
                return NotFound();
            }

            return View(equipos);
        }

        // POST: Equipos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var equipos = await _context.Equipo.FindAsync(id);
            _context.Equipo.Remove(equipos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EquiposExists(int id)
        {
            return _context.Equipo.Any(e => e.idEquipo == id);
        }
    }
}

Proyecto-AspCore-Web/ProyectoWeb/ProyectoApiCore.Web/Controllers/ProyectosController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProyectoApiCore.Web.Contexto;

namespace ProyectoApiCore.Web.Controllers
{
    public class ProyectosController : Controller
    {
        private readonly DbContextDatos _context;

        public ProyectosController(DbContextDatos context)
        {
            _context = context;
        }

        // GET: Proyectos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Proyecto.ToListAsync());
        }

        // GET: Proyectos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proyectos = await _context.Proyecto
                .FirstOrDefaultAsync(m => m.idProyecto == id);
            if (proyectos == null)
            {
                return NotFound();
            }

            return View(proyectos);
        }

        // GET: Proyectos/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Proyectos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("idProyecto,nombreProyecto,descripcionProyecto,logoProyecto")] Proyectos proyectos)
        {
            if (ModelState.IsValid)
            {
                _context.Add(proyectos);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(proyectos);
        }

        // GET: Proyectos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proyectos = await _context.Proyecto.FindAsync(id);
            if (proyectos == null)
            {
                return NotFound();
            }
            return View(proyectos);
        }

        // POST: Proyectos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("idProyecto,nombreProyecto,descripcionProyecto,logoProyecto")] Proyectos proyectos)
        {
            if (id != proyectos.idProyecto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proyectos);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProyectosExists(proyectos.idProyecto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(proyectos);
        }

        // GET: Proyectos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proyectos = await _context.Proyecto
                .FirstOrDefaultAsync(m => m.idProyecto == id);
            if (proyectos == null)
            {
                return NotFound();
            }

            return View(proyectos);
        }

        // POST: Proyectos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var proyectos = await _context.Proyecto.FindAsync(id);
            _context.Proyecto.Remove(proyectos);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProyectosExists(int id)
        {
            return _context.Proyecto.Any(e => e.idProyecto == id);
        }
    }
}

Proyecto-AspCore-Web/ProyectoWeb/ProyectoApiCore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-co">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
   
    <title>@ViewData["Title"] - Trello App</title>
    
    <link rel="icon" type="image/png"      href="~/images/icons/favicon.ico"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <link rel="stylesheet" href="~/css/content.css">
    
    
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/af-2.3.3/b-1.5.6/cr-1.5.0/r-2.2.2/sc-2.0.0/datatables.min.css" />



</head>

<body>
    <div class="header">
        <div class="container-fluid">
            <div class="row ">
                <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary col-12">
                    <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                        <i class="fab fa-algolia"></i>
                        <strong>TrelloApp</strong>
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                                   aria-expanded="false"><i class="fas fa-chalkboard-teacher"> </i>Proyectos</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Proyectos" asp-action="Index">
                                        <i class="far fa-list-alt"></i> Ver Proyectos
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" style="background:rgba(13, 255, 179, 0.5)" asp-controller="Proyectos" asp-action="Create">
                                        <i class="fas fa-plus"></i> Agregar Proyecto
                                    </a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                                   aria-expanded="false"><i class="fas fa-chalkboard-teacher"> </i>Equipos</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="Equipos" asp-action="Index">
                                        <i class="far fa-list-alt"></i> Ver Equipos
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" style="background:rgba(13, 255, 179, 0.5)" asp-controller="Equipos" asp-action="Create">
                                        <i class="fas fa-plus"></i> Agregar Equipo
                                    </a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fab fa-algolia"></i> Tareas</a>
                            </li>
                        </ul>
                    </div>

                </nav>
            </div>
        </div>
    </div>

    @RenderBody()

    <div class="container-fluid fixed-bottom pl-2 pb-3 footer">
        <div class="row">
            <div class="col-12">
                <p>© All rights reserved @DateTime.Now.Year | Andrei, Juan, Breitner</p>
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


    <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/af-2.3.3/b-1.5.6/cr-1.5.0/r-2.2.2/sc-2.0.0/datatables.min.js"></script>


    @RenderSection("Scripts", required: false)
</body>

</html>

Proyecto-AspCore-Web/ProyectoWeb/ProyectoApiCore.Web/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trello App</title>

    <meta name="theme-color" content="#3063A0">

    <meta name="theme-color" content="#3063A0">

    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:400,500,600" rel="stylesheet">

    	
    <link rel="icon" type="image/png"      href="~/images/icons/favicon.ico"/>
    <link rel="stylesheet" type="text/css" href="~/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/animate/animate.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/css-hamburgers/hamburgers.min.css">
    <link rel="stylesheet" type="text/css" href="~/vendor/select2/select2.min.css">
    <link rel="stylesheet" type="text/css" href="~/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/css/main.css">
    
    <script>
        var skin = localStorage.getItem('skin') || 'default';
        var unusedLink = document.querySelector('link[data-skin]:not([data-skin="' + skin + '"])');

        unusedLink.setAttribute('rel', '');
        unusedLink.setAttribute('disabled', true);
    </script>

</head>
<body>

    <!--[if lt IE 10]>
        <div class="page-message" role="alert">Usted está utilizando un <strong>navegador obsoleto</strong>. Por favor, <a class="alert-link" href="http://browsehappy.com/">actualice su navegador</a> para mejorar su experiencia y seguridad.</div>
    <![endif]-->
    
    <main class="auth auth-floated">

        @RenderBody()

        <div id="announcement" class="auth-announcement" style="background-image: url(images/_CAC.CO_2015.png);">
           
        </div>

    </main>


    @*<script src="~/vendor/jquery/jquery.min.js" asp-append-version="true"></script>
    <script src="~/vendor/bootstrap/js/popper.min.js" asp-append-version="true"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.min.js" asp-append-version="true"></script>     
<script src="~/vendor/particles.js/particles.min.js" asp-append-version="true"></script>*@

	
<script src="~/vendor/jquery/jquery-3.2.1.min.js" asp-append-version="true"></script>
<script src="~/vendor/bootstrap/js/popper.js" asp-append-version="true"></script>
<script src="~/vendor/bootstrap/js/bootstrap.min.js" asp-append-version="true"></script>
<script src="~/vendor/select2/select2.min.js" asp-append-version="true"></script>
<script src="~/vendor/tilt/tilt.jquery.min.js" asp-append-version="true"></script>

     <script>
      $(document).on('theme:init', () =>
      {
        particlesJS.load('announcement', 'js/particles.json');
      })

      $('.js-tilt').tilt({
          scale: 1.1
      })
    </script>

<script src="~/js/main.js"></script>

<script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'UA-116692175-1');
    </script>
    
    @RenderSection("Scripts", required: false)
</body>
</html>